# Generated by Django 6.0.3 on 2026-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0002_alter_employerprofile_phone_number_alter_job_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
