# Generated by Django 6.0.3 on 2026-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0006_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='complaint_status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
