# Generated by Django 6.0.3 on 2026-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0007_jobapplication_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
