# Generated by Django 6.0.3 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0008_employerprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_status',
            field=models.CharField(default='not_submitted', max_length=20),
        ),
    ]
