# Generated by Django 6.0.3 on 2026-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0009_jobapplication_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='num_workers',
            field=models.CharField(max_length=50),
        ),
    ]
